var myString;
var myNumb;
var myBool;
var myVar;
var myWish;
var strArr;
var numbArr;
var boolArr;
var strNumbBoth;
myString = 'hello World';
myNumb = 55 - 35;
myBool = true;
myVar = false;
myWish = 'shakib';
strArr = ['Hi', 'FA'];
numbArr = [1, 2, 3, 4];
boolArr = [true, false, true];
strNumbBoth = ['The_Number is ', 5];
console.log(myString);
console.log(myNumb);
console.log(myBool);
console.log(myVar);
console.log(myWish);
console.log(strArr);
console.log(numbArr);
console.log(boolArr);
console.log(strNumbBoth);
